# Generated by Django 4.2.7 on 2023-11-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('room_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
