# Generated by Django 4.2.7 on 2023-12-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
    ]
