# Generated by Django 4.2.7 on 2023-12-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_remove_room_price_per_night'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('room_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('room_desc', models.CharField(max_length=100)),
                ('room_image', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
