# Generated by Django 4.2.7 on 2023-12-02 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_hotelroomtype_delete_roomtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelRoomType',
            new_name='RoomType',
        ),
    ]
