# Generated by Django 4.2.7 on 2023-12-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_rename_hotelroomtype_roomtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomType',
            new_name='HotelRoomType',
        ),
    ]
