# Generated by Django 4.2.7 on 2023-12-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_rename_roomtype_hotelroomtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelRoomType',
            new_name='RoomType',
        ),
    ]
