# Generated by Django 4.2.7 on 2023-12-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0008_rename_hotelroomtype_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_image',
            field=models.ImageField(upload_to='room_images/'),
        ),
    ]
