# Generated by Django 4.2.7 on 2023-12-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0009_alter_roomtype_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_image',
            field=models.CharField(max_length=200),
        ),
    ]
