# Generated by Django 4.2.7 on 2023-12-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0013_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedRoom',
            fields=[
                ('bookedroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('bookedroom_occupancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_room_occupancies', to='HomePage.room')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_guest_ids', to='HomePage.guest')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_rooms', to='HomePage.room')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_room_types', to='HomePage.room')),
            ],
        ),
    ]
