# Generated by Django 4.2.7 on 2023-12-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0014_bookedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.roomtype'),
        ),
    ]
