# Generated by Django 4.2.7 on 2023-12-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0016_billing_bookedservice_booking_service_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_image',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
